package com.dianwoba.zapus.model;

import java.util.Date;

public class ZapusUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.id
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.created_date
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.last_modified_date
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private Date lastModifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.authentication_provider_class
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private String authenticationProviderClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.description
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.email
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.enabled
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.is_external
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private Boolean isExternal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.mobile_phone
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.password
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.role_name
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.timeZone
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private String timezone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.user_language
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private String userLanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.user_name
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.created_user
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private Long createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_user.last_modified_user
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    private Long lastModifiedUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.id
     *
     * @return the value of zapus_user.id
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.id
     *
     * @param id the value for zapus_user.id
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.created_date
     *
     * @return the value of zapus_user.created_date
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.created_date
     *
     * @param createdDate the value for zapus_user.created_date
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.last_modified_date
     *
     * @return the value of zapus_user.last_modified_date
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.last_modified_date
     *
     * @param lastModifiedDate the value for zapus_user.last_modified_date
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.authentication_provider_class
     *
     * @return the value of zapus_user.authentication_provider_class
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public String getAuthenticationProviderClass() {
        return authenticationProviderClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.authentication_provider_class
     *
     * @param authenticationProviderClass the value for zapus_user.authentication_provider_class
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setAuthenticationProviderClass(String authenticationProviderClass) {
        this.authenticationProviderClass = authenticationProviderClass == null ? null : authenticationProviderClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.description
     *
     * @return the value of zapus_user.description
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.description
     *
     * @param description the value for zapus_user.description
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.email
     *
     * @return the value of zapus_user.email
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.email
     *
     * @param email the value for zapus_user.email
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.enabled
     *
     * @return the value of zapus_user.enabled
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.enabled
     *
     * @param enabled the value for zapus_user.enabled
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.is_external
     *
     * @return the value of zapus_user.is_external
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public Boolean getIsExternal() {
        return isExternal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.is_external
     *
     * @param isExternal the value for zapus_user.is_external
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setIsExternal(Boolean isExternal) {
        this.isExternal = isExternal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.mobile_phone
     *
     * @return the value of zapus_user.mobile_phone
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.mobile_phone
     *
     * @param mobilePhone the value for zapus_user.mobile_phone
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.password
     *
     * @return the value of zapus_user.password
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.password
     *
     * @param password the value for zapus_user.password
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.role_name
     *
     * @return the value of zapus_user.role_name
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.role_name
     *
     * @param roleName the value for zapus_user.role_name
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.timeZone
     *
     * @return the value of zapus_user.timeZone
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.timeZone
     *
     * @param timezone the value for zapus_user.timeZone
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setTimezone(String timezone) {
        this.timezone = timezone == null ? null : timezone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.user_language
     *
     * @return the value of zapus_user.user_language
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public String getUserLanguage() {
        return userLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.user_language
     *
     * @param userLanguage the value for zapus_user.user_language
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setUserLanguage(String userLanguage) {
        this.userLanguage = userLanguage == null ? null : userLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.user_name
     *
     * @return the value of zapus_user.user_name
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.user_name
     *
     * @param userName the value for zapus_user.user_name
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.created_user
     *
     * @return the value of zapus_user.created_user
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public Long getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.created_user
     *
     * @param createdUser the value for zapus_user.created_user
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setCreatedUser(Long createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_user.last_modified_user
     *
     * @return the value of zapus_user.last_modified_user
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public Long getLastModifiedUser() {
        return lastModifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_user.last_modified_user
     *
     * @param lastModifiedUser the value for zapus_user.last_modified_user
     *
     * @mbg.generated Tue Jul 11 12:57:23 CST 2017
     */
    public void setLastModifiedUser(Long lastModifiedUser) {
        this.lastModifiedUser = lastModifiedUser;
    }
}