package com.dianwoba.zapus.model;

public class ZapusSystemMonitor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.collect_time
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Long collectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.cpu_used_percentage
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Double cpuUsedPercentage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.crtime
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private String crtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.free_memory
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Long freeMemory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.idle_cpu_value
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Double idleCpuValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.ip
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.monitor_key
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private String monitorKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.load_avg_1
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Double loadAvg1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.load_avg_15
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Double loadAvg15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.load_avg_5
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Double loadAvg5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.message
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.port
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.system
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private String system;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.total_cpu_value
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Double totalCpuValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_system_monitor.total_memory
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Long totalMemory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.id
     *
     * @return the value of zapus_system_monitor.id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.id
     *
     * @param id the value for zapus_system_monitor.id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.collect_time
     *
     * @return the value of zapus_system_monitor.collect_time
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Long getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.collect_time
     *
     * @param collectTime the value for zapus_system_monitor.collect_time
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setCollectTime(Long collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.cpu_used_percentage
     *
     * @return the value of zapus_system_monitor.cpu_used_percentage
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Double getCpuUsedPercentage() {
        return cpuUsedPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.cpu_used_percentage
     *
     * @param cpuUsedPercentage the value for zapus_system_monitor.cpu_used_percentage
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setCpuUsedPercentage(Double cpuUsedPercentage) {
        this.cpuUsedPercentage = cpuUsedPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.crtime
     *
     * @return the value of zapus_system_monitor.crtime
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getCrtime() {
        return crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.crtime
     *
     * @param crtime the value for zapus_system_monitor.crtime
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setCrtime(String crtime) {
        this.crtime = crtime == null ? null : crtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.free_memory
     *
     * @return the value of zapus_system_monitor.free_memory
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Long getFreeMemory() {
        return freeMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.free_memory
     *
     * @param freeMemory the value for zapus_system_monitor.free_memory
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setFreeMemory(Long freeMemory) {
        this.freeMemory = freeMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.idle_cpu_value
     *
     * @return the value of zapus_system_monitor.idle_cpu_value
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Double getIdleCpuValue() {
        return idleCpuValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.idle_cpu_value
     *
     * @param idleCpuValue the value for zapus_system_monitor.idle_cpu_value
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setIdleCpuValue(Double idleCpuValue) {
        this.idleCpuValue = idleCpuValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.ip
     *
     * @return the value of zapus_system_monitor.ip
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.ip
     *
     * @param ip the value for zapus_system_monitor.ip
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.monitor_key
     *
     * @return the value of zapus_system_monitor.monitor_key
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getMonitorKey() {
        return monitorKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.monitor_key
     *
     * @param monitorKey the value for zapus_system_monitor.monitor_key
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setMonitorKey(String monitorKey) {
        this.monitorKey = monitorKey == null ? null : monitorKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.load_avg_1
     *
     * @return the value of zapus_system_monitor.load_avg_1
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Double getLoadAvg1() {
        return loadAvg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.load_avg_1
     *
     * @param loadAvg1 the value for zapus_system_monitor.load_avg_1
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setLoadAvg1(Double loadAvg1) {
        this.loadAvg1 = loadAvg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.load_avg_15
     *
     * @return the value of zapus_system_monitor.load_avg_15
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Double getLoadAvg15() {
        return loadAvg15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.load_avg_15
     *
     * @param loadAvg15 the value for zapus_system_monitor.load_avg_15
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setLoadAvg15(Double loadAvg15) {
        this.loadAvg15 = loadAvg15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.load_avg_5
     *
     * @return the value of zapus_system_monitor.load_avg_5
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Double getLoadAvg5() {
        return loadAvg5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.load_avg_5
     *
     * @param loadAvg5 the value for zapus_system_monitor.load_avg_5
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setLoadAvg5(Double loadAvg5) {
        this.loadAvg5 = loadAvg5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.message
     *
     * @return the value of zapus_system_monitor.message
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.message
     *
     * @param message the value for zapus_system_monitor.message
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.port
     *
     * @return the value of zapus_system_monitor.port
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.port
     *
     * @param port the value for zapus_system_monitor.port
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.system
     *
     * @return the value of zapus_system_monitor.system
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.system
     *
     * @param system the value for zapus_system_monitor.system
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.total_cpu_value
     *
     * @return the value of zapus_system_monitor.total_cpu_value
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Double getTotalCpuValue() {
        return totalCpuValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.total_cpu_value
     *
     * @param totalCpuValue the value for zapus_system_monitor.total_cpu_value
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setTotalCpuValue(Double totalCpuValue) {
        this.totalCpuValue = totalCpuValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_system_monitor.total_memory
     *
     * @return the value of zapus_system_monitor.total_memory
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Long getTotalMemory() {
        return totalMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_system_monitor.total_memory
     *
     * @param totalMemory the value for zapus_system_monitor.total_memory
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setTotalMemory(Long totalMemory) {
        this.totalMemory = totalMemory;
    }
}