package com.dianwoba.zapus.model;

public class ZapusAgent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_agent.id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_agent.approved
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private String approved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_agent.hostName
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private String hostname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_agent.ip
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_agent.region
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private String region;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_agent.id
     *
     * @return the value of zapus_agent.id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_agent.id
     *
     * @param id the value for zapus_agent.id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_agent.approved
     *
     * @return the value of zapus_agent.approved
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getApproved() {
        return approved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_agent.approved
     *
     * @param approved the value for zapus_agent.approved
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setApproved(String approved) {
        this.approved = approved == null ? null : approved.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_agent.hostName
     *
     * @return the value of zapus_agent.hostName
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_agent.hostName
     *
     * @param hostname the value for zapus_agent.hostName
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_agent.ip
     *
     * @return the value of zapus_agent.ip
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_agent.ip
     *
     * @param ip the value for zapus_agent.ip
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_agent.region
     *
     * @return the value of zapus_agent.region
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_agent.region
     *
     * @param region the value for zapus_agent.region
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }
}