package com.dianwoba.zapus.model;

import java.util.Date;

public class ZapusPerftest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.id
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.test_name
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String testName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.tag_string
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String tagString;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.description
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.status
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.ignore_sample_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer ignoreSampleCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.scheduled_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Date scheduledTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.start_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.finish_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.target_hosts
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String targetHosts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.send_mail
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Byte sendMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.use_rampup
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Byte useRampup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.ramp_up_type
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String rampUpType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.threshold
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String threshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.script_name
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String scriptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.duration
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Long duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.run_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer runCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.agent_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer agentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.vuser_per_agent
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer vuserPerAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.processes
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer processes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.ramp_up_init_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer rampUpInitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.ramp_up_init_sleep_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer rampUpInitSleepTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.ramp_up_step
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer rampUpStep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.ramp_up_increment_interval
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer rampUpIncrementInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.threads
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer threads;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.tests
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String tests;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.mean_test_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Double meanTestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.test_time_standard_deviation
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Double testTimeStandardDeviation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.tps
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Double tps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.peak_tps
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Double peakTps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.port
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.test_error_cause
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String testErrorCause;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.distribution_path
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String distributionPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.progress_message
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String progressMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.last_progress_message
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String lastProgressMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.test_comment
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String testComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.script_revision
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Long scriptRevision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.stop_request
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Byte stopRequest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.region
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.safe_distribution
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Byte safeDistribution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.running_sample
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String runningSample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.agent_stat
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String agentStat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.monitor_stat
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String monitorStat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.sampling_interval
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer samplingInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.param
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.create_date
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.create_user_id
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.last_modified_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Date lastModifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.last_modified_user_id
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private Integer lastModifiedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.errors
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    private String errors;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.id
     *
     * @return the value of zapus_perftest.id
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.id
     *
     * @param id the value for zapus_perftest.id
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.test_name
     *
     * @return the value of zapus_perftest.test_name
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.test_name
     *
     * @param testName the value for zapus_perftest.test_name
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setTestName(String testName) {
        this.testName = testName == null ? null : testName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.tag_string
     *
     * @return the value of zapus_perftest.tag_string
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getTagString() {
        return tagString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.tag_string
     *
     * @param tagString the value for zapus_perftest.tag_string
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setTagString(String tagString) {
        this.tagString = tagString == null ? null : tagString.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.description
     *
     * @return the value of zapus_perftest.description
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.description
     *
     * @param description the value for zapus_perftest.description
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.status
     *
     * @return the value of zapus_perftest.status
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.status
     *
     * @param status the value for zapus_perftest.status
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.ignore_sample_count
     *
     * @return the value of zapus_perftest.ignore_sample_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getIgnoreSampleCount() {
        return ignoreSampleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.ignore_sample_count
     *
     * @param ignoreSampleCount the value for zapus_perftest.ignore_sample_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setIgnoreSampleCount(Integer ignoreSampleCount) {
        this.ignoreSampleCount = ignoreSampleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.scheduled_time
     *
     * @return the value of zapus_perftest.scheduled_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Date getScheduledTime() {
        return scheduledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.scheduled_time
     *
     * @param scheduledTime the value for zapus_perftest.scheduled_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setScheduledTime(Date scheduledTime) {
        this.scheduledTime = scheduledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.start_time
     *
     * @return the value of zapus_perftest.start_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.start_time
     *
     * @param startTime the value for zapus_perftest.start_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.finish_time
     *
     * @return the value of zapus_perftest.finish_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.finish_time
     *
     * @param finishTime the value for zapus_perftest.finish_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.target_hosts
     *
     * @return the value of zapus_perftest.target_hosts
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getTargetHosts() {
        return targetHosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.target_hosts
     *
     * @param targetHosts the value for zapus_perftest.target_hosts
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setTargetHosts(String targetHosts) {
        this.targetHosts = targetHosts == null ? null : targetHosts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.send_mail
     *
     * @return the value of zapus_perftest.send_mail
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Byte getSendMail() {
        return sendMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.send_mail
     *
     * @param sendMail the value for zapus_perftest.send_mail
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setSendMail(Byte sendMail) {
        this.sendMail = sendMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.use_rampup
     *
     * @return the value of zapus_perftest.use_rampup
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Byte getUseRampup() {
        return useRampup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.use_rampup
     *
     * @param useRampup the value for zapus_perftest.use_rampup
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setUseRampup(Byte useRampup) {
        this.useRampup = useRampup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.ramp_up_type
     *
     * @return the value of zapus_perftest.ramp_up_type
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getRampUpType() {
        return rampUpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.ramp_up_type
     *
     * @param rampUpType the value for zapus_perftest.ramp_up_type
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setRampUpType(String rampUpType) {
        this.rampUpType = rampUpType == null ? null : rampUpType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.threshold
     *
     * @return the value of zapus_perftest.threshold
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getThreshold() {
        return threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.threshold
     *
     * @param threshold the value for zapus_perftest.threshold
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setThreshold(String threshold) {
        this.threshold = threshold == null ? null : threshold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.script_name
     *
     * @return the value of zapus_perftest.script_name
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getScriptName() {
        return scriptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.script_name
     *
     * @param scriptName the value for zapus_perftest.script_name
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setScriptName(String scriptName) {
        this.scriptName = scriptName == null ? null : scriptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.duration
     *
     * @return the value of zapus_perftest.duration
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.duration
     *
     * @param duration the value for zapus_perftest.duration
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.run_count
     *
     * @return the value of zapus_perftest.run_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getRunCount() {
        return runCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.run_count
     *
     * @param runCount the value for zapus_perftest.run_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setRunCount(Integer runCount) {
        this.runCount = runCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.agent_count
     *
     * @return the value of zapus_perftest.agent_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getAgentCount() {
        return agentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.agent_count
     *
     * @param agentCount the value for zapus_perftest.agent_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setAgentCount(Integer agentCount) {
        this.agentCount = agentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.vuser_per_agent
     *
     * @return the value of zapus_perftest.vuser_per_agent
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getVuserPerAgent() {
        return vuserPerAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.vuser_per_agent
     *
     * @param vuserPerAgent the value for zapus_perftest.vuser_per_agent
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setVuserPerAgent(Integer vuserPerAgent) {
        this.vuserPerAgent = vuserPerAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.processes
     *
     * @return the value of zapus_perftest.processes
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getProcesses() {
        return processes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.processes
     *
     * @param processes the value for zapus_perftest.processes
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setProcesses(Integer processes) {
        this.processes = processes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.ramp_up_init_count
     *
     * @return the value of zapus_perftest.ramp_up_init_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getRampUpInitCount() {
        return rampUpInitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.ramp_up_init_count
     *
     * @param rampUpInitCount the value for zapus_perftest.ramp_up_init_count
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setRampUpInitCount(Integer rampUpInitCount) {
        this.rampUpInitCount = rampUpInitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.ramp_up_init_sleep_time
     *
     * @return the value of zapus_perftest.ramp_up_init_sleep_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getRampUpInitSleepTime() {
        return rampUpInitSleepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.ramp_up_init_sleep_time
     *
     * @param rampUpInitSleepTime the value for zapus_perftest.ramp_up_init_sleep_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setRampUpInitSleepTime(Integer rampUpInitSleepTime) {
        this.rampUpInitSleepTime = rampUpInitSleepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.ramp_up_step
     *
     * @return the value of zapus_perftest.ramp_up_step
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getRampUpStep() {
        return rampUpStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.ramp_up_step
     *
     * @param rampUpStep the value for zapus_perftest.ramp_up_step
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setRampUpStep(Integer rampUpStep) {
        this.rampUpStep = rampUpStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.ramp_up_increment_interval
     *
     * @return the value of zapus_perftest.ramp_up_increment_interval
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getRampUpIncrementInterval() {
        return rampUpIncrementInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.ramp_up_increment_interval
     *
     * @param rampUpIncrementInterval the value for zapus_perftest.ramp_up_increment_interval
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setRampUpIncrementInterval(Integer rampUpIncrementInterval) {
        this.rampUpIncrementInterval = rampUpIncrementInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.threads
     *
     * @return the value of zapus_perftest.threads
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getThreads() {
        return threads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.threads
     *
     * @param threads the value for zapus_perftest.threads
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setThreads(Integer threads) {
        this.threads = threads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.tests
     *
     * @return the value of zapus_perftest.tests
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getTests() {
        return tests;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.tests
     *
     * @param tests the value for zapus_perftest.tests
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setTests(String tests) {
        this.tests = tests == null ? null : tests.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.mean_test_time
     *
     * @return the value of zapus_perftest.mean_test_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Double getMeanTestTime() {
        return meanTestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.mean_test_time
     *
     * @param meanTestTime the value for zapus_perftest.mean_test_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setMeanTestTime(Double meanTestTime) {
        this.meanTestTime = meanTestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.test_time_standard_deviation
     *
     * @return the value of zapus_perftest.test_time_standard_deviation
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Double getTestTimeStandardDeviation() {
        return testTimeStandardDeviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.test_time_standard_deviation
     *
     * @param testTimeStandardDeviation the value for zapus_perftest.test_time_standard_deviation
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setTestTimeStandardDeviation(Double testTimeStandardDeviation) {
        this.testTimeStandardDeviation = testTimeStandardDeviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.tps
     *
     * @return the value of zapus_perftest.tps
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Double getTps() {
        return tps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.tps
     *
     * @param tps the value for zapus_perftest.tps
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setTps(Double tps) {
        this.tps = tps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.peak_tps
     *
     * @return the value of zapus_perftest.peak_tps
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Double getPeakTps() {
        return peakTps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.peak_tps
     *
     * @param peakTps the value for zapus_perftest.peak_tps
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setPeakTps(Double peakTps) {
        this.peakTps = peakTps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.port
     *
     * @return the value of zapus_perftest.port
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.port
     *
     * @param port the value for zapus_perftest.port
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.test_error_cause
     *
     * @return the value of zapus_perftest.test_error_cause
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getTestErrorCause() {
        return testErrorCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.test_error_cause
     *
     * @param testErrorCause the value for zapus_perftest.test_error_cause
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setTestErrorCause(String testErrorCause) {
        this.testErrorCause = testErrorCause == null ? null : testErrorCause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.distribution_path
     *
     * @return the value of zapus_perftest.distribution_path
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getDistributionPath() {
        return distributionPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.distribution_path
     *
     * @param distributionPath the value for zapus_perftest.distribution_path
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setDistributionPath(String distributionPath) {
        this.distributionPath = distributionPath == null ? null : distributionPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.progress_message
     *
     * @return the value of zapus_perftest.progress_message
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getProgressMessage() {
        return progressMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.progress_message
     *
     * @param progressMessage the value for zapus_perftest.progress_message
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setProgressMessage(String progressMessage) {
        this.progressMessage = progressMessage == null ? null : progressMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.last_progress_message
     *
     * @return the value of zapus_perftest.last_progress_message
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getLastProgressMessage() {
        return lastProgressMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.last_progress_message
     *
     * @param lastProgressMessage the value for zapus_perftest.last_progress_message
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setLastProgressMessage(String lastProgressMessage) {
        this.lastProgressMessage = lastProgressMessage == null ? null : lastProgressMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.test_comment
     *
     * @return the value of zapus_perftest.test_comment
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getTestComment() {
        return testComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.test_comment
     *
     * @param testComment the value for zapus_perftest.test_comment
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setTestComment(String testComment) {
        this.testComment = testComment == null ? null : testComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.script_revision
     *
     * @return the value of zapus_perftest.script_revision
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Long getScriptRevision() {
        return scriptRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.script_revision
     *
     * @param scriptRevision the value for zapus_perftest.script_revision
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setScriptRevision(Long scriptRevision) {
        this.scriptRevision = scriptRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.stop_request
     *
     * @return the value of zapus_perftest.stop_request
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Byte getStopRequest() {
        return stopRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.stop_request
     *
     * @param stopRequest the value for zapus_perftest.stop_request
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setStopRequest(Byte stopRequest) {
        this.stopRequest = stopRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.region
     *
     * @return the value of zapus_perftest.region
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.region
     *
     * @param region the value for zapus_perftest.region
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.safe_distribution
     *
     * @return the value of zapus_perftest.safe_distribution
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Byte getSafeDistribution() {
        return safeDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.safe_distribution
     *
     * @param safeDistribution the value for zapus_perftest.safe_distribution
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setSafeDistribution(Byte safeDistribution) {
        this.safeDistribution = safeDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.running_sample
     *
     * @return the value of zapus_perftest.running_sample
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getRunningSample() {
        return runningSample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.running_sample
     *
     * @param runningSample the value for zapus_perftest.running_sample
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setRunningSample(String runningSample) {
        this.runningSample = runningSample == null ? null : runningSample.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.agent_stat
     *
     * @return the value of zapus_perftest.agent_stat
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getAgentStat() {
        return agentStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.agent_stat
     *
     * @param agentStat the value for zapus_perftest.agent_stat
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setAgentStat(String agentStat) {
        this.agentStat = agentStat == null ? null : agentStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.monitor_stat
     *
     * @return the value of zapus_perftest.monitor_stat
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getMonitorStat() {
        return monitorStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.monitor_stat
     *
     * @param monitorStat the value for zapus_perftest.monitor_stat
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setMonitorStat(String monitorStat) {
        this.monitorStat = monitorStat == null ? null : monitorStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.sampling_interval
     *
     * @return the value of zapus_perftest.sampling_interval
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getSamplingInterval() {
        return samplingInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.sampling_interval
     *
     * @param samplingInterval the value for zapus_perftest.sampling_interval
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setSamplingInterval(Integer samplingInterval) {
        this.samplingInterval = samplingInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.param
     *
     * @return the value of zapus_perftest.param
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.param
     *
     * @param param the value for zapus_perftest.param
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.create_date
     *
     * @return the value of zapus_perftest.create_date
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.create_date
     *
     * @param createDate the value for zapus_perftest.create_date
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.create_user_id
     *
     * @return the value of zapus_perftest.create_user_id
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.create_user_id
     *
     * @param createUserId the value for zapus_perftest.create_user_id
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.last_modified_time
     *
     * @return the value of zapus_perftest.last_modified_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.last_modified_time
     *
     * @param lastModifiedTime the value for zapus_perftest.last_modified_time
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.last_modified_user_id
     *
     * @return the value of zapus_perftest.last_modified_user_id
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public Integer getLastModifiedUserId() {
        return lastModifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.last_modified_user_id
     *
     * @param lastModifiedUserId the value for zapus_perftest.last_modified_user_id
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setLastModifiedUserId(Integer lastModifiedUserId) {
        this.lastModifiedUserId = lastModifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.errors
     *
     * @return the value of zapus_perftest.errors
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public String getErrors() {
        return errors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.errors
     *
     * @param errors the value for zapus_perftest.errors
     *
     * @mbg.generated Tue Jul 11 16:32:23 CST 2017
     */
    public void setErrors(String errors) {
        this.errors = errors == null ? null : errors.trim();
    }
}