package com.dianwoba.zapus.model;

import java.util.ArrayList;
import java.util.List;

public class ZapusSystemMonitorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public ZapusSystemMonitorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCollectTimeIsNull() {
            addCriterion("collect_time is null");
            return (Criteria) this;
        }

        public Criteria andCollectTimeIsNotNull() {
            addCriterion("collect_time is not null");
            return (Criteria) this;
        }

        public Criteria andCollectTimeEqualTo(Long value) {
            addCriterion("collect_time =", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeNotEqualTo(Long value) {
            addCriterion("collect_time <>", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeGreaterThan(Long value) {
            addCriterion("collect_time >", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("collect_time >=", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeLessThan(Long value) {
            addCriterion("collect_time <", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeLessThanOrEqualTo(Long value) {
            addCriterion("collect_time <=", value, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeIn(List<Long> values) {
            addCriterion("collect_time in", values, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeNotIn(List<Long> values) {
            addCriterion("collect_time not in", values, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeBetween(Long value1, Long value2) {
            addCriterion("collect_time between", value1, value2, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCollectTimeNotBetween(Long value1, Long value2) {
            addCriterion("collect_time not between", value1, value2, "collectTime");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageIsNull() {
            addCriterion("cpu_used_percentage is null");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageIsNotNull() {
            addCriterion("cpu_used_percentage is not null");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageEqualTo(Double value) {
            addCriterion("cpu_used_percentage =", value, "cpuUsedPercentage");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageNotEqualTo(Double value) {
            addCriterion("cpu_used_percentage <>", value, "cpuUsedPercentage");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageGreaterThan(Double value) {
            addCriterion("cpu_used_percentage >", value, "cpuUsedPercentage");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageGreaterThanOrEqualTo(Double value) {
            addCriterion("cpu_used_percentage >=", value, "cpuUsedPercentage");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageLessThan(Double value) {
            addCriterion("cpu_used_percentage <", value, "cpuUsedPercentage");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageLessThanOrEqualTo(Double value) {
            addCriterion("cpu_used_percentage <=", value, "cpuUsedPercentage");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageIn(List<Double> values) {
            addCriterion("cpu_used_percentage in", values, "cpuUsedPercentage");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageNotIn(List<Double> values) {
            addCriterion("cpu_used_percentage not in", values, "cpuUsedPercentage");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageBetween(Double value1, Double value2) {
            addCriterion("cpu_used_percentage between", value1, value2, "cpuUsedPercentage");
            return (Criteria) this;
        }

        public Criteria andCpuUsedPercentageNotBetween(Double value1, Double value2) {
            addCriterion("cpu_used_percentage not between", value1, value2, "cpuUsedPercentage");
            return (Criteria) this;
        }

        public Criteria andCrtimeIsNull() {
            addCriterion("crtime is null");
            return (Criteria) this;
        }

        public Criteria andCrtimeIsNotNull() {
            addCriterion("crtime is not null");
            return (Criteria) this;
        }

        public Criteria andCrtimeEqualTo(String value) {
            addCriterion("crtime =", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeNotEqualTo(String value) {
            addCriterion("crtime <>", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeGreaterThan(String value) {
            addCriterion("crtime >", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeGreaterThanOrEqualTo(String value) {
            addCriterion("crtime >=", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeLessThan(String value) {
            addCriterion("crtime <", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeLessThanOrEqualTo(String value) {
            addCriterion("crtime <=", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeLike(String value) {
            addCriterion("crtime like", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeNotLike(String value) {
            addCriterion("crtime not like", value, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeIn(List<String> values) {
            addCriterion("crtime in", values, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeNotIn(List<String> values) {
            addCriterion("crtime not in", values, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeBetween(String value1, String value2) {
            addCriterion("crtime between", value1, value2, "crtime");
            return (Criteria) this;
        }

        public Criteria andCrtimeNotBetween(String value1, String value2) {
            addCriterion("crtime not between", value1, value2, "crtime");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryIsNull() {
            addCriterion("free_memory is null");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryIsNotNull() {
            addCriterion("free_memory is not null");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryEqualTo(Long value) {
            addCriterion("free_memory =", value, "freeMemory");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryNotEqualTo(Long value) {
            addCriterion("free_memory <>", value, "freeMemory");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryGreaterThan(Long value) {
            addCriterion("free_memory >", value, "freeMemory");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryGreaterThanOrEqualTo(Long value) {
            addCriterion("free_memory >=", value, "freeMemory");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryLessThan(Long value) {
            addCriterion("free_memory <", value, "freeMemory");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryLessThanOrEqualTo(Long value) {
            addCriterion("free_memory <=", value, "freeMemory");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryIn(List<Long> values) {
            addCriterion("free_memory in", values, "freeMemory");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryNotIn(List<Long> values) {
            addCriterion("free_memory not in", values, "freeMemory");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryBetween(Long value1, Long value2) {
            addCriterion("free_memory between", value1, value2, "freeMemory");
            return (Criteria) this;
        }

        public Criteria andFreeMemoryNotBetween(Long value1, Long value2) {
            addCriterion("free_memory not between", value1, value2, "freeMemory");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueIsNull() {
            addCriterion("idle_cpu_value is null");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueIsNotNull() {
            addCriterion("idle_cpu_value is not null");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueEqualTo(Double value) {
            addCriterion("idle_cpu_value =", value, "idleCpuValue");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueNotEqualTo(Double value) {
            addCriterion("idle_cpu_value <>", value, "idleCpuValue");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueGreaterThan(Double value) {
            addCriterion("idle_cpu_value >", value, "idleCpuValue");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueGreaterThanOrEqualTo(Double value) {
            addCriterion("idle_cpu_value >=", value, "idleCpuValue");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueLessThan(Double value) {
            addCriterion("idle_cpu_value <", value, "idleCpuValue");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueLessThanOrEqualTo(Double value) {
            addCriterion("idle_cpu_value <=", value, "idleCpuValue");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueIn(List<Double> values) {
            addCriterion("idle_cpu_value in", values, "idleCpuValue");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueNotIn(List<Double> values) {
            addCriterion("idle_cpu_value not in", values, "idleCpuValue");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueBetween(Double value1, Double value2) {
            addCriterion("idle_cpu_value between", value1, value2, "idleCpuValue");
            return (Criteria) this;
        }

        public Criteria andIdleCpuValueNotBetween(Double value1, Double value2) {
            addCriterion("idle_cpu_value not between", value1, value2, "idleCpuValue");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyIsNull() {
            addCriterion("monitor_key is null");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyIsNotNull() {
            addCriterion("monitor_key is not null");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyEqualTo(String value) {
            addCriterion("monitor_key =", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyNotEqualTo(String value) {
            addCriterion("monitor_key <>", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyGreaterThan(String value) {
            addCriterion("monitor_key >", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyGreaterThanOrEqualTo(String value) {
            addCriterion("monitor_key >=", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyLessThan(String value) {
            addCriterion("monitor_key <", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyLessThanOrEqualTo(String value) {
            addCriterion("monitor_key <=", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyLike(String value) {
            addCriterion("monitor_key like", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyNotLike(String value) {
            addCriterion("monitor_key not like", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyIn(List<String> values) {
            addCriterion("monitor_key in", values, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyNotIn(List<String> values) {
            addCriterion("monitor_key not in", values, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyBetween(String value1, String value2) {
            addCriterion("monitor_key between", value1, value2, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyNotBetween(String value1, String value2) {
            addCriterion("monitor_key not between", value1, value2, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1IsNull() {
            addCriterion("load_avg_1 is null");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1IsNotNull() {
            addCriterion("load_avg_1 is not null");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1EqualTo(Double value) {
            addCriterion("load_avg_1 =", value, "loadAvg1");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1NotEqualTo(Double value) {
            addCriterion("load_avg_1 <>", value, "loadAvg1");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1GreaterThan(Double value) {
            addCriterion("load_avg_1 >", value, "loadAvg1");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1GreaterThanOrEqualTo(Double value) {
            addCriterion("load_avg_1 >=", value, "loadAvg1");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1LessThan(Double value) {
            addCriterion("load_avg_1 <", value, "loadAvg1");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1LessThanOrEqualTo(Double value) {
            addCriterion("load_avg_1 <=", value, "loadAvg1");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1In(List<Double> values) {
            addCriterion("load_avg_1 in", values, "loadAvg1");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1NotIn(List<Double> values) {
            addCriterion("load_avg_1 not in", values, "loadAvg1");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1Between(Double value1, Double value2) {
            addCriterion("load_avg_1 between", value1, value2, "loadAvg1");
            return (Criteria) this;
        }

        public Criteria andLoadAvg1NotBetween(Double value1, Double value2) {
            addCriterion("load_avg_1 not between", value1, value2, "loadAvg1");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15IsNull() {
            addCriterion("load_avg_15 is null");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15IsNotNull() {
            addCriterion("load_avg_15 is not null");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15EqualTo(Double value) {
            addCriterion("load_avg_15 =", value, "loadAvg15");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15NotEqualTo(Double value) {
            addCriterion("load_avg_15 <>", value, "loadAvg15");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15GreaterThan(Double value) {
            addCriterion("load_avg_15 >", value, "loadAvg15");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15GreaterThanOrEqualTo(Double value) {
            addCriterion("load_avg_15 >=", value, "loadAvg15");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15LessThan(Double value) {
            addCriterion("load_avg_15 <", value, "loadAvg15");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15LessThanOrEqualTo(Double value) {
            addCriterion("load_avg_15 <=", value, "loadAvg15");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15In(List<Double> values) {
            addCriterion("load_avg_15 in", values, "loadAvg15");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15NotIn(List<Double> values) {
            addCriterion("load_avg_15 not in", values, "loadAvg15");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15Between(Double value1, Double value2) {
            addCriterion("load_avg_15 between", value1, value2, "loadAvg15");
            return (Criteria) this;
        }

        public Criteria andLoadAvg15NotBetween(Double value1, Double value2) {
            addCriterion("load_avg_15 not between", value1, value2, "loadAvg15");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5IsNull() {
            addCriterion("load_avg_5 is null");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5IsNotNull() {
            addCriterion("load_avg_5 is not null");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5EqualTo(Double value) {
            addCriterion("load_avg_5 =", value, "loadAvg5");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5NotEqualTo(Double value) {
            addCriterion("load_avg_5 <>", value, "loadAvg5");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5GreaterThan(Double value) {
            addCriterion("load_avg_5 >", value, "loadAvg5");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5GreaterThanOrEqualTo(Double value) {
            addCriterion("load_avg_5 >=", value, "loadAvg5");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5LessThan(Double value) {
            addCriterion("load_avg_5 <", value, "loadAvg5");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5LessThanOrEqualTo(Double value) {
            addCriterion("load_avg_5 <=", value, "loadAvg5");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5In(List<Double> values) {
            addCriterion("load_avg_5 in", values, "loadAvg5");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5NotIn(List<Double> values) {
            addCriterion("load_avg_5 not in", values, "loadAvg5");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5Between(Double value1, Double value2) {
            addCriterion("load_avg_5 between", value1, value2, "loadAvg5");
            return (Criteria) this;
        }

        public Criteria andLoadAvg5NotBetween(Double value1, Double value2) {
            addCriterion("load_avg_5 not between", value1, value2, "loadAvg5");
            return (Criteria) this;
        }

        public Criteria andMessageIsNull() {
            addCriterion("message is null");
            return (Criteria) this;
        }

        public Criteria andMessageIsNotNull() {
            addCriterion("message is not null");
            return (Criteria) this;
        }

        public Criteria andMessageEqualTo(String value) {
            addCriterion("message =", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotEqualTo(String value) {
            addCriterion("message <>", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThan(String value) {
            addCriterion("message >", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThanOrEqualTo(String value) {
            addCriterion("message >=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThan(String value) {
            addCriterion("message <", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThanOrEqualTo(String value) {
            addCriterion("message <=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLike(String value) {
            addCriterion("message like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotLike(String value) {
            addCriterion("message not like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageIn(List<String> values) {
            addCriterion("message in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotIn(List<String> values) {
            addCriterion("message not in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageBetween(String value1, String value2) {
            addCriterion("message between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotBetween(String value1, String value2) {
            addCriterion("message not between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andPortIsNull() {
            addCriterion("port is null");
            return (Criteria) this;
        }

        public Criteria andPortIsNotNull() {
            addCriterion("port is not null");
            return (Criteria) this;
        }

        public Criteria andPortEqualTo(Integer value) {
            addCriterion("port =", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotEqualTo(Integer value) {
            addCriterion("port <>", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThan(Integer value) {
            addCriterion("port >", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("port >=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThan(Integer value) {
            addCriterion("port <", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThanOrEqualTo(Integer value) {
            addCriterion("port <=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortIn(List<Integer> values) {
            addCriterion("port in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotIn(List<Integer> values) {
            addCriterion("port not in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortBetween(Integer value1, Integer value2) {
            addCriterion("port between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotBetween(Integer value1, Integer value2) {
            addCriterion("port not between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andSystemIsNull() {
            addCriterion("system is null");
            return (Criteria) this;
        }

        public Criteria andSystemIsNotNull() {
            addCriterion("system is not null");
            return (Criteria) this;
        }

        public Criteria andSystemEqualTo(String value) {
            addCriterion("system =", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotEqualTo(String value) {
            addCriterion("system <>", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemGreaterThan(String value) {
            addCriterion("system >", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemGreaterThanOrEqualTo(String value) {
            addCriterion("system >=", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLessThan(String value) {
            addCriterion("system <", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLessThanOrEqualTo(String value) {
            addCriterion("system <=", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLike(String value) {
            addCriterion("system like", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotLike(String value) {
            addCriterion("system not like", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemIn(List<String> values) {
            addCriterion("system in", values, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotIn(List<String> values) {
            addCriterion("system not in", values, "system");
            return (Criteria) this;
        }

        public Criteria andSystemBetween(String value1, String value2) {
            addCriterion("system between", value1, value2, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotBetween(String value1, String value2) {
            addCriterion("system not between", value1, value2, "system");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueIsNull() {
            addCriterion("total_cpu_value is null");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueIsNotNull() {
            addCriterion("total_cpu_value is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueEqualTo(Double value) {
            addCriterion("total_cpu_value =", value, "totalCpuValue");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueNotEqualTo(Double value) {
            addCriterion("total_cpu_value <>", value, "totalCpuValue");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueGreaterThan(Double value) {
            addCriterion("total_cpu_value >", value, "totalCpuValue");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueGreaterThanOrEqualTo(Double value) {
            addCriterion("total_cpu_value >=", value, "totalCpuValue");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueLessThan(Double value) {
            addCriterion("total_cpu_value <", value, "totalCpuValue");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueLessThanOrEqualTo(Double value) {
            addCriterion("total_cpu_value <=", value, "totalCpuValue");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueIn(List<Double> values) {
            addCriterion("total_cpu_value in", values, "totalCpuValue");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueNotIn(List<Double> values) {
            addCriterion("total_cpu_value not in", values, "totalCpuValue");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueBetween(Double value1, Double value2) {
            addCriterion("total_cpu_value between", value1, value2, "totalCpuValue");
            return (Criteria) this;
        }

        public Criteria andTotalCpuValueNotBetween(Double value1, Double value2) {
            addCriterion("total_cpu_value not between", value1, value2, "totalCpuValue");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryIsNull() {
            addCriterion("total_memory is null");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryIsNotNull() {
            addCriterion("total_memory is not null");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryEqualTo(Long value) {
            addCriterion("total_memory =", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryNotEqualTo(Long value) {
            addCriterion("total_memory <>", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryGreaterThan(Long value) {
            addCriterion("total_memory >", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryGreaterThanOrEqualTo(Long value) {
            addCriterion("total_memory >=", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryLessThan(Long value) {
            addCriterion("total_memory <", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryLessThanOrEqualTo(Long value) {
            addCriterion("total_memory <=", value, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryIn(List<Long> values) {
            addCriterion("total_memory in", values, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryNotIn(List<Long> values) {
            addCriterion("total_memory not in", values, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryBetween(Long value1, Long value2) {
            addCriterion("total_memory between", value1, value2, "totalMemory");
            return (Criteria) this;
        }

        public Criteria andTotalMemoryNotBetween(Long value1, Long value2) {
            addCriterion("total_memory not between", value1, value2, "totalMemory");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 10 17:22:31 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zapus_system_monitor
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}