package com.dianwoba.zapus.model;

public class ZapusPerftestWithBLOBs extends ZapusPerftest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.tests
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private String tests;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perftest.errors
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private String errors;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.tests
     *
     * @return the value of zapus_perftest.tests
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getTests() {
        return tests;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.tests
     *
     * @param tests the value for zapus_perftest.tests
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setTests(String tests) {
        this.tests = tests == null ? null : tests.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perftest.errors
     *
     * @return the value of zapus_perftest.errors
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public String getErrors() {
        return errors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perftest.errors
     *
     * @param errors the value for zapus_perftest.errors
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setErrors(String errors) {
        this.errors = errors == null ? null : errors.trim();
    }
}