package com.dianwoba.zapus.model;

public class ZapusPerfTestTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perf_test_tag.perf_test_id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Long perfTestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zapus_perf_test_tag.tag_id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    private Long tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perf_test_tag.perf_test_id
     *
     * @return the value of zapus_perf_test_tag.perf_test_id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Long getPerfTestId() {
        return perfTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perf_test_tag.perf_test_id
     *
     * @param perfTestId the value for zapus_perf_test_tag.perf_test_id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setPerfTestId(Long perfTestId) {
        this.perfTestId = perfTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zapus_perf_test_tag.tag_id
     *
     * @return the value of zapus_perf_test_tag.tag_id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zapus_perf_test_tag.tag_id
     *
     * @param tagId the value for zapus_perf_test_tag.tag_id
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}