package com.dianwoba.zapus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.dianwoba.zapus.model.ZapusAgent;
import com.dianwoba.zapus.model.ZapusAgentExample;

public interface ZapusAgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_agent
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    long countByExample(ZapusAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_agent
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int deleteByExample(ZapusAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_agent
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_agent
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int insert(ZapusAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_agent
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int insertSelective(ZapusAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_agent
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    List<ZapusAgent> selectByExample(ZapusAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_agent
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    ZapusAgent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_agent
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") ZapusAgent record,
        @Param("example") ZapusAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_agent
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByExample(@Param("record") ZapusAgent record,
        @Param("example") ZapusAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_agent
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByPrimaryKeySelective(ZapusAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_agent
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByPrimaryKey(ZapusAgent record);
}