package com.dianwoba.zapus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.dianwoba.zapus.model.ZapusTag;
import com.dianwoba.zapus.model.ZapusTagExample;

public interface ZapusTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_tag
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    long countByExample(ZapusTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_tag
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int deleteByExample(ZapusTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_tag
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_tag
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int insert(ZapusTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_tag
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int insertSelective(ZapusTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_tag
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    List<ZapusTag> selectByExample(ZapusTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_tag
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    ZapusTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_tag
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") ZapusTag record,
        @Param("example") ZapusTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_tag
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByExample(@Param("record") ZapusTag record, @Param("example") ZapusTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_tag
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByPrimaryKeySelective(ZapusTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_tag
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByPrimaryKey(ZapusTag record);
}