package com.dianwoba.zapus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.dianwoba.zapus.model.ZapusPerftest;
import com.dianwoba.zapus.model.ZapusPerftestExample;
import com.dianwoba.zapus.model.ZapusPerftestWithBLOBs;

public interface ZapusPerftestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    long countByExample(ZapusPerftestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int deleteByExample(ZapusPerftestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int insert(ZapusPerftestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int insertSelective(ZapusPerftestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    List<ZapusPerftestWithBLOBs> selectByExampleWithBLOBs(ZapusPerftestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    List<ZapusPerftest> selectByExample(ZapusPerftestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    ZapusPerftestWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") ZapusPerftestWithBLOBs record,
        @Param("example") ZapusPerftestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ZapusPerftestWithBLOBs record,
        @Param("example") ZapusPerftestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByExample(@Param("record") ZapusPerftest record,
        @Param("example") ZapusPerftestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByPrimaryKeySelective(ZapusPerftestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ZapusPerftestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_perftest
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByPrimaryKey(ZapusPerftest record);
}