package com.dianwoba.zapus.mapper;

import com.dianwoba.zapus.model.ZapusUser;
import com.dianwoba.zapus.model.ZapusUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZapusUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_nuser
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    long countByExample(ZapusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_nuser
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int deleteByExample(ZapusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_nuser
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_nuser
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int insert(ZapusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_nuser
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int insertSelective(ZapusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_nuser
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    List<ZapusUser> selectByExample(ZapusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_nuser
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    ZapusUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_nuser
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") ZapusUser record,
        @Param("example") ZapusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_nuser
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByExample(@Param("record") ZapusUser record,
        @Param("example") ZapusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_nuser
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByPrimaryKeySelective(ZapusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zapus_nuser
     *
     * @mbg.generated Mon Jul 10 17:22:31 CST 2017
     */
    int updateByPrimaryKey(ZapusUser record);
}